I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/extremis/coteries/transhumanistes/evts_Transhumanistes.rpy", line 39, in script
    $ texte = blessures_.SoignerMaladieAleatoire(situation_)
  File "game/extremis/coteries/transhumanistes/evts_Transhumanistes.rpy", line 39, in <module>
    $ texte = blessures_.SoignerMaladieAleatoire(situation_)
AttributeError: CollectionBlessures instance has no attribute 'SoignerMaladieAleatoire'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/extremis/coteries/transhumanistes/evts_Transhumanistes.rpy", line 39, in script
    $ texte = blessures_.SoignerMaladieAleatoire(situation_)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/extremis/coteries/transhumanistes/evts_Transhumanistes.rpy", line 39, in <module>
    $ texte = blessures_.SoignerMaladieAleatoire(situation_)
AttributeError: CollectionBlessures instance has no attribute 'SoignerMaladieAleatoire'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Wed Mar 17 21:32:46 2021
