I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 60, in script
    $ situation_.TourSuivant()
  File "game/script.rpy", line 60, in <module>
    $ situation_.TourSuivant()
AttributeError: 'dict' object has no attribute 'Values'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 60, in script
    $ situation_.TourSuivant()
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 60, in <module>
    $ situation_.TourSuivant()
  File "despin/gen_vie/situation.py", line 400, in TourSuivant
  File "despin/gen_vie/situation.py", line 376, in AvanceDeXJours
AttributeError: 'dict' object has no attribute 'Values'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Sun Mar 28 18:55:12 2021
