I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/extremis/coteries/templiers/evts_UnivTempliers.rpy", line 327, in script
    $ prenom = situation_[identite.Identite.C_PRENOM]
  File "game/extremis/coteries/templiers/evts_UnivTempliers.rpy", line 327, in <module>
    $ prenom = situation_[identite.Identite.C_PRENOM]
NameError: name 'identite' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/extremis/coteries/templiers/evts_UnivTempliers.rpy", line 327, in script
    $ prenom = situation_[identite.Identite.C_PRENOM]
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/extremis/coteries/templiers/evts_UnivTempliers.rpy", line 327, in <module>
    $ prenom = situation_[identite.Identite.C_PRENOM]
NameError: name 'identite' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Wed Feb 17 21:52:28 2021
