I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/evts_generaux/naissance.rpy", line 84, in script
    $ genererParents(situation_)
  File "game/evts_generaux/naissance.rpy", line 84, in <module>
    $ genererParents(situation_)
  File "game/evts_generaux/naissance.rpy", line 75, in genererParents
    pere = pnj.GenererPNJPapa(situation)
NameError: global name 'age' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/evts_generaux/naissance.rpy", line 84, in script
    $ genererParents(situation_)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/evts_generaux/naissance.rpy", line 84, in <module>
    $ genererParents(situation_)
  File "game/evts_generaux/naissance.rpy", line 75, in genererParents
    pere = pnj.GenererPNJPapa(situation)
  File "extremis/humanite/pnj.py", line 81, in GenererPNJPapa
NameError: global name 'age' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Wed Mar 24 21:51:42 2021
