I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/evts_generaux/naissance.rpy", line 151, in script
    $ genererParents(situation_)
  File "game/evts_generaux/naissance.rpy", line 151, in <module>
    $ genererParents(situation_)
  File "game/evts_generaux/naissance.rpy", line 139, in genererParents
    coterieObj = coteries_[mereObj.coterie_]
NameError: global name 'mereObj' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/evts_generaux/naissance.rpy", line 151, in script
    $ genererParents(situation_)
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/evts_generaux/naissance.rpy", line 151, in <module>
    $ genererParents(situation_)
  File "game/evts_generaux/naissance.rpy", line 139, in genererParents
    coterieObj = coteries_[mereObj.coterie_]
NameError: global name 'mereObj' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
DestinExtremis 1.0
Mon Jun  7 21:29:13 2021
