I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/generationUnivers.rpy", line 1, in script
    init -2 python:
  File "game/generationUnivers.rpy", line 13, in <module>
    coteries_ = collection_coteries.CollectionCoteries()
UnboundLocalError: local variable 'transhumanistes' referenced before assignment

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/generationUnivers.rpy", line 1, in script
    init -2 python:
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/generationUnivers.rpy", line 13, in <module>
    coteries_ = collection_coteries.CollectionCoteries()
  File "extremis/coteries/collection_coteries.py", line 13, in __init__
UnboundLocalError: local variable 'transhumanistes' referenced before assignment

Windows-8-6.2.9200
Ren'Py 7.3.5.606
 
Sat Jan 30 16:28:52 2021
