I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/extremis/humanite/sante/evts_maladies.rpy", line 30, in script
    "[texteMaladie]"
Exception: The displayable with id 'what' was not given the exact contents of the what variable given to the say screen.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/extremis/humanite/sante/evts_maladies.rpy", line 30, in script
    "[texteMaladie]"
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 708, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\exports.py", line 1345, in say
    who(what, *args, **kwargs)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\character.py", line 1142, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\character.py", line 842, in do_display
    **display_args)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\character.py", line 575, in display_say
    raise Exception("The displayable with id 'what' was not given the exact contents of the what variable given to the say screen.")
Exception: The displayable with id 'what' was not given the exact contents of the what variable given to the say screen.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Thu Feb 11 21:58:53 2021
