I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 39, in script
    $ date_.TourSuivant()
  File "game/script.rpy", line 39, in <module>
    $ date_.TourSuivant()
NameError: name 'date_' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 39, in script
    $ date_.TourSuivant()
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 39, in <module>
    $ date_.TourSuivant()
NameError: name 'date_' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Sat Jan 23 21:43:44 2021
