I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/extremis/humanite/amour/evts_rencontresAmoureuses.rpy", line 34, in script
    $ amoureuse = pnj.GenererRelationAmoureuse(situation_)
  File "game/extremis/humanite/amour/evts_rencontresAmoureuses.rpy", line 34, in <module>
    $ amoureuse = pnj.GenererRelationAmoureuse(situation_)
NameError: global name 'Trait' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/extremis/humanite/amour/evts_rencontresAmoureuses.rpy", line 34, in script
    $ amoureuse = pnj.GenererRelationAmoureuse(situation_)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/extremis/humanite/amour/evts_rencontresAmoureuses.rpy", line 34, in <module>
    $ amoureuse = pnj.GenererRelationAmoureuse(situation_)
  File "extremis/humanite/pnj.py", line 144, in GenererRelationAmoureuse
  File "extremis/humanite/amour/relationAmoureuse.py", line 81, in CalculerAmabiliteHommePremierContact
NameError: global name 'Trait' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Sun Apr 04 13:19:51 2021
